---
# tasks file for MicroJoe.shaarli

- name: Install php dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php-cli
    - php-fpm
    - php-gd
    - php-intl
    - php-xml
    - php-mbstring

- name: Make sure Shaarli group exists
  group:
    name: "{{ shaarli_group }}"

- name: Make sure Shaarli user exists
  user:
    name: "{{ shaarli_user }}"
    group: "{{ shaarli_group }}"

- name: Make sure Shaarli base directory exists
  file:
    path: "{{ shaarli_base }}"
    state: directory

- name: Download and extract Shaarli
  unarchive:
    src: "{{ shaarli_source }}"
    dest: "{{ shaarli_base }}"
    remote_src: true
    extra_opts: ["--strip-components=1"]
    group: "{{ shaarli_group }}"
    owner: "{{ shaarli_user }}"
    mode: u=rwX,g=rwX,o=rX
  args:
    creates: "{{ shaarli_base }}/index.php"

- name: Install php version file
  template:
    src: templates/shaarli_version.php.j2
    dest: "{{ shaarli_base }}/shaarli_version.php"
    owner: "{{ shaarli_user }}"
    group: "{{ shaarli_group }}"

- name: Install robots.txt deny all file
  copy:
    src: files/robots.txt
    dest: "{{ shaarli_base }}/robots.txt"
    owner: "{{ shaarli_user }}"
    group: "{{ shaarli_group }}"
  when: shaarli_deny_robots

- name: Install nginx configuration file {{ shaarli_nginx_filename }}
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-available/{{ shaarli_nginx_filename }}
    owner: root
    group: root
  notify: restart nginx
